### ISSUE TITLE
@import now also forbitten in replace

### ISSUE THREAD

**Issue by jogibear9988** [calebdwilliams/construct-style-sheets#49]
https://developers.google.com/web/updates/2020/05/chrome-84-deps-rems#import_rules_in_cssstylesheetreplace_removed

**Comment by calebdwilliams** [comment]
Hey, I've been waiting for Chrome to implement this behavior before adding to the polyfill so we can stick as close to the behavior of Chrome as possible. That should happen with a release this month, so it's coming soon.

If you're interested in contributing, let me know. Otherwise, I'll take it on once the final behavior is known.

**Comment by calebdwilliams** [comment]
Hey @jogibear9988, I just wanted to let you know that 2.4.0 now warns and removes `@import`s. Thanks for raising the issue.
